src/Entity/Measuerement.php
<?php

namespace App\Entity;

use App\Repository\MeasuerementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MeasuerementRepository::class)
 */
class Measuerement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=City::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city_name;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=0)
     */
    private $temperature;

    /**
     * @ORM\Column(type="integer")
     */
    private $humidity;

    /**
     * @ORM\Column(type="integer")
     */
    private $chance_of_precision;

    /**
     * @ORM\Column(type="integer")
     */
    private $wind_speed;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCityName(): ?string
    {
        return $this->city_name;
    }

    public function setCityName(string $city_name): self
    {
        $this->city_name = $city_name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(int $humidity): self
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getChanceOfPrecision(): ?int
    {
        return $this->chance_of_precision;
    }

    public function setChanceOfPrecision(int $chance_of_precision): self
    {
        $this->chance_of_precision = $chance_of_precision;

        return $this;
    }

    public function getWindSpeed(): ?int
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(int $wind_speed): self
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/MeasuerementType.php
<?php

namespace App\Form;

use App\Entity\Measuerement;
use App\Entity\City;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class MeasuerementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('city_name')
            ->add('date', DateType::class)
            ->add('temperature', NumberType::class, [
                'html5' => true,
            ])
            ->add('humidity', NumberType::class, [
                'html5' => true,
            ])
            ->add('chance_of_precision', NumberType::class, [
                'html5' => true,
            ])
            ->add('wind_speed', NumberType::class, [
                'html5' => true,
            ])
            ->add('description')
            ->add('city', EntityType::class, [
                'class' => City::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measuerement::class,
        ]);
    }
}

src/Controller/MeasuerementController.php
<?php

namespace App\Controller;

use App\Entity\Measuerement;
use App\Form\MeasuerementType;
use App\Repository\MeasuerementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/measuerement")
 */
class MeasuerementController extends AbstractController
{
    /**
     * @Route("/", name="measuerement_index", methods={"GET"})
     */
    public function index(MeasuerementRepository $measuerementRepository): Response
    {
        return $this->render('measuerement/index.html.twig', [
            'measuerements' => $measuerementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="measuerement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $measuerement = new Measuerement();
        $form = $this->createForm(MeasuerementType::class, $measuerement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($measuerement);
            $entityManager->flush();

            return $this->redirectToRoute('measuerement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measuerement/new.html.twig', [
            'measuerement' => $measuerement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="measuerement_show", methods={"GET"})
     */
    public function show(Measuerement $measuerement): Response
    {
        return $this->render('measuerement/show.html.twig', [
            'measuerement' => $measuerement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="measuerement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Measuerement $measuerement): Response
    {
        $form = $this->createForm(MeasuerementType::class, $measuerement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('measuerement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measuerement/edit.html.twig', [
            'measuerement' => $measuerement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="measuerement_delete", methods={"POST"})
     */
    public function delete(Request $request, Measuerement $measuerement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measuerement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($measuerement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('measuerement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measuerement/_delete_form.html.twig
<form method="post" action="{{ path('measuerement_delete', {'id': measuerement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measuerement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/measuerement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/measuerement/edit.html.twig
{% include 'base.html.twig' %}

{% block body %}
    <h1>Edit Measuerement</h1>

    {{ include('measuerement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('measuerement_index') }}">back to list</a>

    {{ include('measuerement/_delete_form.html.twig') }}
{% endblock %}

templates/measuerement/index.html.twig
{% include 'base.html.twig' %}

{% block body %}
    <h1>Measuerement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>City_name</th>
                <th>Date</th>
                <th>Temperature</th>
                <th>Humidity</th>
                <th>Chance_of_precision</th>
                <th>Wind_speed</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measuerement in measuerements %}
            <tr>
                <td>{{ measuerement.id }}</td>
                <td>{{ measuerement.cityName }}</td>
                <td>{{ measuerement.date ? measuerement.date|date('Y-m-d') : '' }}</td>
                <td>{{ measuerement.temperature }}</td>
                <td>{{ measuerement.humidity }}</td>
                <td>{{ measuerement.chanceOfPrecision }}</td>
                <td>{{ measuerement.windSpeed }}</td>
                <td>{{ measuerement.description }}</td>
                <td>
                    <a href="{{ path('measuerement_show', {'id': measuerement.id}) }}">show</a>
                    <a href="{{ path('measuerement_edit', {'id': measuerement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('measuerement_new') }}">Create new</a>

{% endblock %}

templates/measuerement/new.html.twig
{% include 'base.html.twig' %}

{% block body %}
    <h1>Create new Measuerement</h1>

    {{ include('measuerement/_form.html.twig') }}

    <a href="{{ path('measuerement_index') }}">back to list</a>
{% endblock %}

templates/measuerement/show.html.twig
{% include 'base.html.twig' %}

{% block body %}
    <h1>Measuerement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measuerement.id }}</td>
            </tr>
            <tr>
                <th>City_name</th>
                <td>{{ measuerement.cityName }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ measuerement.date ? measuerement.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ measuerement.temperature }}</td>
            </tr>
            <tr>
                <th>Humidity</th>
                <td>{{ measuerement.humidity }}</td>
            </tr>
            <tr>
                <th>Chance_of_precision</th>
                <td>{{ measuerement.chanceOfPrecision }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ measuerement.windSpeed }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ measuerement.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('measuerement_index') }}">back to list</a>

    <a href="{{ path('measuerement_edit', {'id': measuerement.id}) }}">edit</a>

    {{ include('measuerement/_delete_form.html.twig') }}
{% endblock %}